# Generated by Django 3.0.3 on 2020-02-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_item_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='caption',
            field=models.CharField(db_index=True, max_length=256, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='item',
            name='source',
            field=models.CharField(max_length=512, verbose_name='Source'),
        ),
    ]
