# Generated by Django 3.0.3 on 2020-03-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_item_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='source',
            field=models.URLField(max_length=512, verbose_name='Source'),
        ),
    ]
